### ISSUE TITLE
E/flutter (32024) nable to load asset: assets/flutter_i18n/zh_CN.yaml

### ISSUE THREAD

**Issue by dancheng99** [ilteoood/flutter_i18n#111]
localizationsDelegates: [
              FlutterI18nDelegate(
                  translationLoader: FileTranslationLoader(
                      useCountryCode: false,
                      fallbackFile: 'en_US',
                      basePath: 'assets/flutter_i18n',
                      forcedLocale: Locale('en_US'))),
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate,
            ],

assets/flutter_i18n/en_US.json 
assets/flutter_i18n/zh_CN.json 

why 

```
E/flutter (32024): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Unable to load asset: assets/flutter_i18n/zh_CN.yaml
E/flutter (32024): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
E/flutter (32024): <asynchronous suspension>
E/flutter (32024): #1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67:33)
E/flutter (32024): #2      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:162:56)
E/flutter (32024): #3      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
E/flutter (32024): #4      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:162:27)
E/flutter (32024): #5      FileTranslationLoader.loadString (package:flutter_i18n/loaders/file_translation_loader.dart:46:24)
E/flutter (32024): #6      BaseDecodeStrategy.loadFileContent (package:flutter_i18n/loaders/decoders/base_decode_strategy.dart:27:24)
E/flutter (32024): #7      BaseDecodeStrategy.decode (package:flutter_i18n/loaders/decoders/base_decode_strategy.dart:14:36)
E/flutter (32024): #8      FileTranslationLoader._executeStrategies.<anonymous closure> (package:flutter_i18n/loaders/file_translation_loader.dart:77:49)
E/flutter (32024): #9      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
E/flutter (32024): #10     ListIterable.toList (dart:_internal/iterable.dart:221:19)
E/flutter (32024): #11     FileTranslationLoader._executeStrategies (package:flutter_i18n/loaders/file_translation_loader.dart:78:10)
E/flutter (32024): #12     FileTranslationLoader.loadFile (package:flutter_i18n/loaders/file_translation_loader.dart:70:49)
E/flutter (32024): #13     FileTranslationLoader._loadCurrentTranslation (package:flutter_i18n/loaders/file_translation_loader.dart:53:32)
E/flutter (32024): #14     FileTranslationLoader.load (package:flutter_i18n/loaders/file_translation_loader.dart:39:11)
E/flutter (32024): #15     FlutterI18n.load (package:flutter_i18n/flutter_i18n.dart:36:42)
E/flutter (32024): #16     FlutterI18nDelegate.load (package:flutter_i18n/flutter_i18n_delegate.dart:35:32)
E/flutter (32024): #17     _loadAll (package:flutter/src/widgets/localizations.dart:58:49)
E/flutter (32024): #18     _LocalizationsState.load (package:flutter/src/widgets/localizations.dart:509:62)
E/flutter (32024): #19     _LocalizationsState.initState (package:flutter/src/widgets/localizations.dart:474:5)
E/flutter (32024): #20     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
E/flutter (32024): #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (32024): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (32024): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (32024): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (32024): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (32024): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (32024): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (32024): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (32024): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (32024): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (32024): #31     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
E/flutter (32024): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (32024): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (32024): #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
E/flutter (32024): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (32024): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
```

**Comment by ilteoood** [comment]
Hi,
after the assets insert, did you tried to clean and rebuild?
Can you post the assets folder structure?
Can you post your pubsec?

**Comment by dancheng99** [comment]
hi 
I deleted folder of the build and rebuild

pubsec
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
    # sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  english_words: ^3.1.0
  flutter_bloc: ^4.0.1
  fluro: "^1.6.3"
  provider: ^4.0.4
  flutter_swiper: ^1.1.6
  json_annotation: ^2.3.0
  dio: ^3.0.9
  flutter_spinkit: ^3.1.0
  event_bus: ^1.1.1
  flutter_html: ^0.9.6
  flutter_screenutil: ^2.1.0
  fluttertoast: ^3.1.0
  shared_preferences: ^0.5.3+4
  city_pickers: ^0.1.23
  flutter_easyrefresh: ^2.0.3
  flutter_webview_plugin: ^0.3.7
  flutter_cache_manager: ^1.2.2
  cached_network_image: ^2.0.0-rc
  package_info: ^0.4.0+2
  flutter_i18n: ^0.16.2
  yaml: ^2.2.0
  xml2json: ^4.2.0
  merge_map: ^1.0.2
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
build_runner: ^1.6.1
json_serializable: ^3.0.0

  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    -  assets/flutter_i18n/
```

![Uploading 1.jpg…]()

**Comment by dancheng99** [comment]
> Hi,
> after the assets insert, did you tried to clean and rebuild?
> Can you post the assets folder structure?
> Can you post your pubsec?



> Hi,
> after the assets insert, did you tried to clean and rebuild?
> Can you post the assets folder structure?
> Can you post your pubsec?

hi 
I have deleted folder of the build and rebuilded the app
but the result is not change

pubsec
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
    # sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  english_words: ^3.1.0
  flutter_bloc: ^4.0.1
  fluro: "^1.6.3"
  provider: ^4.0.4
  flutter_swiper: ^1.1.6
  json_annotation: ^2.3.0
  dio: ^3.0.9
  flutter_spinkit: ^3.1.0
  event_bus: ^1.1.1
  flutter_html: ^0.9.6
  flutter_screenutil: ^2.1.0
  fluttertoast: ^3.1.0
  shared_preferences: ^0.5.3+4
  city_pickers: ^0.1.23
  flutter_easyrefresh: ^2.0.3
  flutter_webview_plugin: ^0.3.7
  flutter_cache_manager: ^1.2.2
  cached_network_image: ^2.0.0-rc
  package_info: ^0.4.0+2
  flutter_i18n: ^0.16.2
  yaml: ^2.2.0
  xml2json: ^4.2.0
  merge_map: ^1.0.2
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
build_runner: ^1.6.1
json_serializable: ^3.0.0

  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    -  assets/flutter_i18n/
```

the assets folder structure
app\assets\flutter_i18n\en_US.json
