### ISSUE TITLE
[Question] Basic Text Formatting (bold, italic, underscore)

### ISSUE THREAD

**Issue by moseskarunia** [ilteoood/flutter_i18n#156]
Hi, is it possible to use basic text formatting with translate?

For example, I want to display "Hello **world**!"

```yaml
page:
  main:
    message: Hello **world**! 
```
