### ISSUE TITLE
Unable to load asset

### ISSUE THREAD

**Issue by agordeev** [ilteoood/flutter_i18n#52]
First of all, thanks for the great library!
I use `yaml` files and use code from example project. The error I get is: 

```FlutterError (Unable to load asset: assets/i18n/fr.json)```

 on line:

```
await flutterI18nDelegate.load(null);
```
The reason of this error is this function:

```dart
  Future<void> _loadFile(final String fileName) async {
    try {
      decodedMap = await rootBundle
          .loadString('$_basePath/$fileName.json')
          .then((jsonString) => json.decode(jsonString));
    } on FlutterError catch (_) {
      var yamlNode = await rootBundle
          .loadString('$_basePath/$fileName.yaml')
          .then((yamlString) => loadYamlNode(yamlString));
      decodedMap = _convertYaml(yamlNode);
    }
  }
```
For some reason debugger considers the exception as uncaught and therefore stops program. This is quite annoying.
I think a better solution is to let the user specify which file type he uses for translation.

**Comment by ilteoood** [comment]
Hi @agordeev,
I know that could be a stupid question, but did you tried to clean all the project after you inserted the json file in the asset folder?

Sometimes the compiler don't consider the json in the assert folder as a change

**Comment by agordeev** [comment]
I use YAML, not JSON. And yes, I did `flutter clean`.

**Comment by agordeev** [comment]
My issue is exactly as this one: https://github.com/ilteoood/flutter_i18n/issues/15

**Comment by ilteoood** [comment]
Sorry for the response delay, it's a really difficult moment for me at work.
I hope to release your changes before the end of the day :)

**Comment by agordeev** [comment]
Hmm, interesting. You merged my pull request, but then updated the code back to try..catch block :) What's the reason? The issue still persists in the latest version because of using try..catch.

**Comment by ilteoood** [comment]
Hi,
I reverted and improved the version with the try catch because your version was implemented in the wrong way. The File. Exist method verify if the file exist on the device file system, not in the assets

**Comment by agordeev** [comment]
Hmm... However, it worked for me.
Anyway, try..catch still produces the issue described here and #15 when using YAML

**Comment by ilteoood** [comment]
That solution worked for you because with that solution you load only the yaml file, avoiding the json.
BTW, can u send me the structure of your assets folder, your pubsec and the locale of your device?

**Comment by agordeev** [comment]
pubspec:

```
...
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/i18n/en.yaml
    - assets/i18n/fr.yaml
...
```

Locale: fr_FR.
