### ISSUE TITLE
Problem everytime when calling the the translate function of flutter i18n.

### ISSUE THREAD

**Issue by itsbinay** [ilteoood/flutter_i18n#59]
```
The method 'getdecodedMap' was called on null.
Receiver: null
Tried calling: getdecodedMap()
```

this error is invoked everytime when I call the FlutterI18n.translate(context,key) function

Snippet of code:
![Screenshot 2020-01-14 at 6 15 44 PM](https://user-images.githubusercontent.com/44058187/72335558-1b8a6500-36fa-11ea-9369-56ec4a3e210a.png)

Error:
![Screenshot 2020-01-14 at 6 16 12 PM](https://user-images.githubusercontent.com/44058187/72335589-293fea80-36fa-11ea-9222-8e7cbc4443e8.png)

**Comment by itsbinay** [comment]
This is what the pubspec.yaml looks like

```
name: xxxxxapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+3
  sqflite: ^1.2.0
  path_provider: ^1.5.1
  easy_localization: ^1.3.1
  flutter_i18n: ^0.8.3

  qr_code_scanner: ^0.0.12
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/i18n/en_US.json
    - assets/i18n/zh_CN.json
    - assets/i18n/zh_HK.json
    - assets/images/bgimages/
    - assets/images/logoimage/
    - assets/images/default_banner/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
This is what the file directory looks like
![Screenshot 2020-01-15 at 9 54 07 AM](https://user-images.githubusercontent.com/44058187/72398162-0b679980-377d-11ea-8a06-cb837527c11b.png)

I have resolved back to trying to use json file so this is what it looks like for now, my en_US.json

```
{
    "logintitle":"User Login",
    "dashboardtitle":"Event",
    "sessiontitle":"Session",
    "checkInTitle":"check in",

    "langSelect":"Please Select Language",
    
    "username":"Username",
    "password":"Password",
    
    "loginbutton":"Log In",
    "checkInButton":"Check In",
    "checkedInButton":"Checked In",
    
    "logout":"Log Out",
    "search":"Search",
    "edit":"Edit",
    "save":"Save",
    "cancel":"Cancel",
 
    "guestList":"Guest List",
    "checkedIn":"Checked-In",
    "walkedIn":"Walked-In",
    "pendingArrival":"Pending Arrival",

    "status":"Status",
    "online":"Wifi Online",
    "offline":"Offline",
    "syncText":"items to sync",

    "profile":"Profile",
    "info":"Basic Info",

    "firstName":"First Name",
    "lastName":"Last Name",
    "company":"Company",
    "department":"Department",
    "jobTitle":"Job Title",
    "email":"Email",
    "mobile":"Mobile",
    "officePhone":"Office Phone",
    "remarks":"Remarks"
}
```

The loading of is exactly as stated in the example, (main.dart) the entry point of the app is as follows:
```
import 'package:flutter/material.dart';
import 'package:flutter_i18n/flutter_i18n_delegate.dart';
import 'package:xxxxxapp/login/login.dart';//
import 'package:flutter_localizations/flutter_localizations.dart';


Future main() async{
  final FlutterI18nDelegate  flutterI18nDelegate = FlutterI18nDelegate(
    useCountryCode: true,
    path: 'assets/i18n',
    fallbackFile: 'en_US',
    forcedLocale: Locale('en','US')
  );

  WidgetsFlutterBinding.ensureInitialized();
  await flutterI18nDelegate.load(Locale('en','US'));
  print("Loaded");
  runApp(MyApp(flutterI18nDelegate));
}

class MyApp extends StatelessWidget{
  final FlutterI18nDelegate flutterI18nDelegate;
  
  MyApp(this.flutterI18nDelegate);
  @override
  Widget build(BuildContext context){
    return new MaterialApp(
      title: 'Login Page',
      home: LoginPage(),
      localizationsDelegates: [
        this.flutterI18nDelegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
    );
  }
}
```
