### ISSUE TITLE
Add pluralization rules

### ISSUE THREAD

**Issue by shlima** [ilteoood/flutter_i18n#66]
Could you please add support of pluralization rules with support of `translationParams`? like

```yaml
key:
  one: "....{count} ball"
  few: "....{count} balls"
  many: "....{count} balls"
  other: "....{count} balls"
```

Pluralization rules might to be customizable by a user for each locale code
